Core Module SDK Documentation: bc_co2
bc_co2
Driver for BigClown CO2 Sensor.
Data Structures
struct bc_co2_sensor_driver_t
CO2 Sensor driver.
Enumerations
enum bc_co2_sensor_event_t {
BC_CO2_SENSOR_EVENT_ERROR = 0,
BC_CO2_SENSOR_EVENT_UPDATE = 1
}
Callback events.
enum bc_co2_sensor_calibration_t {
BC_CO2_SENSOR_CALIBRATION_BACKGROUND_UNFILTERED = 0x50,
BC_CO2_SENSOR_CALIBRATION_BACKGROUND_FILTERED = 0x51,
BC_CO2_SENSOR_CALIBRATION_BACKGROUND_UNFILTERED_RF = 0x52,
BC_CO2_SENSOR_CALIBRATION_BACKGROUND_FILTERED_RF = 0x53,
BC_CO2_SENSOR_CALIBRATION_ABC = 0x70,
BC_CO2_SENSOR_CALIBRATION_ABC_RF = 0x72
}
Calibration.
Functions
void bc_co2_sensor_init (bc_co2_sensor_t *self, const bc_co2_sensor_driver_t *driver)
Initialize BigClown CO2 Sensor.
void bc_co2_sensor_set_event_handler (bc_co2_sensor_t *self, void(*event_handler)(bc_co2_sensor_event_t, void *), void *event_param)
Set callback function.
void bc_co2_sensor_set_update_interval (bc_co2_sensor_t *self, bc_tick_t interval)
Set measurement interval.
bool bc_co2_sensor_measure (bc_co2_sensor_t *self)
Start measurement manually.
bool bc_co2_sensor_get_concentration_ppm (bc_co2_sensor_t *self, float *ppm)
Get CO2 concentration in ppm (parts per million)
void bc_co2_sensor_calibration (bc_co2_sensor_t *self, bc_co2_sensor_calibration_t calibration)
Request sensor calibration.
Detailed Description
Driver for BigClown CO2 Sensor.
Enumeration Type Documentation
enum bc_co2_sensor_calibration_t
Calibration.
Enumerator
BC_CO2_SENSOR_CALIBRATION_BACKGROUND_UNFILTERED
Background calibration using unfiltered data.
BC_CO2_SENSOR_CALIBRATION_BACKGROUND_FILTERED
Background calibration using filtered data.
BC_CO2_SENSOR_CALIBRATION_BACKGROUND_UNFILTERED_RF
Background calibration using unfiltered data + reset filters.
BC_CO2_SENSOR_CALIBRATION_BACKGROUND_FILTERED_RF
Background calibration using filtered data + reset filters.
BC_CO2_SENSOR_CALIBRATION_ABC
ABC (based on filtered data)
BC_CO2_SENSOR_CALIBRATION_ABC_RF
ABC (based on filtered data) + reset filters.
Definition at line 25 of file bc_co2_sensor.h.
enum bc_co2_sensor_event_t
Callback events.
Enumerator
BC_CO2_SENSOR_EVENT_ERROR
Error event.
BC_CO2_SENSOR_EVENT_UPDATE
Update event.
Definition at line 13 of file bc_co2_sensor.h.
Function Documentation
void bc_co2_sensor_calibration (bc_co2_sensor_t * self, bc_co2_sensor_calibration_t calibration)
Request sensor calibration.
Parameters
[in] self Instance
[in] calibration Calibration type
Definition at line 88 of file bc_co2_sensor.c.
Referenced by bc_module_co2_calibration().
bool bc_co2_sensor_get_concentration_ppm (bc_co2_sensor_t * self, float * ppm)
Get CO2 concentration in ppm (parts per million)
Parameters
[in] self Instance
[out] ppm Pointer to variable where result will be stored
Returns
true On success
false On failure
Definition at line 76 of file bc_co2_sensor.c.
Referenced by bc_module_co2_get_concentration_ppm().
bool bc_co2_sensor_measure (bc_co2_sensor_t * self)
Start measurement manually.
Parameters
[in] self Instance
Returns
true On success
False When other measurement is in progress
Definition at line 58 of file bc_co2_sensor.c.
Referenced by bc_co2_sensor_calibration(), bc_co2_sensor_set_update_interval(), and bc_module_co2_measure().
void bc_co2_sensor_set_event_handler (bc_co2_sensor_t * self, void(*)(bc_co2_sensor_event_t, void *) event_handler, void * event_param)
Set callback function.
Parameters
[in] self Instance
[in] event_handler Function address
[in] event_param Optional event parameter (can be NULL)
Definition at line 36 of file bc_co2_sensor.c.
Referenced by bc_module_co2_set_event_handler().
void bc_co2_sensor_set_update_interval (bc_co2_sensor_t * self, bc_tick_t interval)
Set measurement interval.
Parameters
[in] self Instance
[in] interval Measurement interval
Definition at line 42 of file bc_co2_sensor.c.
Referenced by bc_module_co2_set_update_interval().